<a href="https://colab.research.google.com/github/129Ashish/129Ashish11/blob/main/6_Pipeline_modified_using_Dataset%26DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Code FLow :
# 1.Load the Dataset
# 2.Basic Preprocessing
# 3.Training Process :
#       a.Create the Model
#       b.Forward Pass
#       c.Loss Calculation
#       d.Backprop
#       e.Parameters update
# 4.Model Evaluation

# Dataset Loading

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns = ['id','Unnamed: 32'],inplace =True)

In [ ]:
df.shape

(569, 31)

In [ ]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

# Train Test Split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.3)

In [ ]:
print(f"Shape of X_train : {X_train.shape}")
print(f"Shape of X_test : {X_test.shape}")
print(f"Shape of y_train : {y_train.shape}")
print(f"Shape of y_test : {y_test.shape}")

Shape of X_train : (398, 30)
Shape of X_test : (171, 30)
Shape of y_train : (398,)
Shape of y_test : (171,)

# Scaling

In [ ]:
# scaling is used to send similar type of data to our model
scaler = StandardScaler()
X_train =scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 2.33716425,  0.0582888 ,  2.53800924, ...,  2.69901012,
         1.89681745,  0.74467415],
       [ 0.14574078,  1.06875635,  0.11344799, ..., -0.70741739,
        -0.65390848, -0.66320444],
       [-0.09775072, -1.42837611, -0.15761321, ..., -0.8833203 ,
        -0.15308101, -0.91344475],
       ...,
       [-1.01442459,  0.18604906, -0.9033438 , ...,  0.47715955,
        -0.52911758,  1.96874789],
       [-0.99150774,  1.34750602, -0.9924484 , ..., -0.83196403,
         0.82195186, -0.1643847 ],
       [-0.44436802, -0.08108604, -0.41326847, ..., -0.35084497,
        -1.32112381, -0.69531492]])

In [ ]:
X_test

array([[ 0.68428668, -0.26227332,  0.61434911, ..., -0.37267907,
        -0.86688494, -1.09337418],
       [ 0.11995933, -1.26344922,  0.08388525, ..., -0.13173514,
        -0.51414267, -0.35095767],
       [ 0.22594974,  0.72264218,  0.42697961, ...,  2.03014853,
        -0.08153423,  1.71961484],
       ...,
       [ 0.73871419,  0.18140323,  0.63516794, ..., -0.43203092,
         2.93174995, -0.4544863 ],
       [-0.89984035, -0.51547094, -0.83755628, ...,  0.61554471,
        -0.62395866,  0.60239149],
       [ 0.02542734,  0.25805939,  0.02351063, ...,  0.28342033,
        -0.63394194, -0.32438348]])

# Label Encoding

In [ ]:
y_train #our diagnosis is in alphabet format i.e. B and M which is not understandable by our machine so we have to encode these alphabets

108    M
90     B
295    B
436    B
334    B
      ..
564    M
415    B
376    B
248    B
355    B
Name: diagnosis, Length: 398, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train # now 0 : B and 1 : M

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0])

# Numpy arrays to Pytorch Tensors

In [ ]:
X_train_tensor = torch.FloatTensor(X_train)
X_test_tensor = torch.FloatTensor(X_test)
y_train_tensor = torch.LongTensor(y_train)
y_test_tensor = torch.LongTensor(y_test)

In [ ]:
print(f"shape of X_train_tensor : {X_train_tensor.shape}")
print(f"shape of X_test_tensor : {X_test_tensor.shape}")
print(f"shape of y_train_tensor : {y_train_tensor.shape}")
print(f"shape of y_test_tensor : {y_test_tensor.shape}")

shape of X_train_tensor : torch.Size([398, 30])
shape of X_test_tensor : torch.Size([171, 30])
shape of y_train_tensor : torch.Size([398])
shape of y_test_tensor : torch.Size([171])

In [ ]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features=features
    self.labels=labels


  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [ ]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_dataset[10]

(tensor([-0.4730,  1.0734, -0.3279, -0.5171,  1.5696,  2.6377,  1.7753,  0.9475,
          0.8284,  2.7783, -0.4204,  0.7199, -0.4526, -0.4272,  0.0479,  2.7453,
          1.5829,  0.4428, -0.3273,  2.3985, -0.2453,  2.3974, -0.2867, -0.3014,
          2.2761,  5.1034,  4.0494,  1.6227,  2.4143,  6.8130]),
 tensor(1))

In [ ]:
test_dataset[10]

(tensor([ 1.8129,  0.5484,  1.7469,  1.8765, -0.3797,  0.1703,  0.1267,  0.7509,
         -0.7575, -1.0418,  0.7434, -0.5501,  0.8277,  0.9723, -0.2736, -0.3690,
         -0.2640,  0.4919, -0.7718, -0.7182,  1.6826,  0.0780,  1.6289,  1.6386,
         -0.0306, -0.1205, -0.0138,  0.9384, -0.5092, -0.9461]),
 tensor(1))

In [ ]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

# Defining the Model

In [ ]:
# class MySimpleNN():
#   def __init__(self,X):
#     self.weights = torch.rand(X.shape[1],1,dtype=torch.float32,requires_grad=True)#weights matrix dim 30 1
#     self.bias = torch.zeros(1,dtype=torch.float32,requires_grad=True)

#   def forward(self,X):
#     z = torch.matmul(X,self.weights)  +self.bias
#     y_pred =torch.sigmoid(z)
#     return y_pred

# # Binary loss function of cross-entropy
#   def loss_function(self,y_pred,y):
#     #CLamp predictions to avoid log(0)
#     epsilon = 1e-7
#     y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

#     #Calculate loss
#     loss = -(y_train_tensor  * torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()
#     return loss

In [ ]:
import torch
import torch.nn as nn

class MySimpleNN(torch.nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

# Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 30

In [ ]:
#define loss function
loss_function = nn.BCELoss()

# Training Pipeline

In [ ]:
# create model
# model = MySimpleNN(X_train_tensor)
# model.weights #matrix of 30 by 1

In [ ]:
# model.bias# a scalar with item 0

tensor([0.], requires_grad=True)

In [ ]:
#define model
model = MySimpleNN(X_train_tensor.shape[1])
#define loop

#define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:

    #forward pass
    y_pred=model(batch_features)

    #loss calculate
    loss=loss_function(y_pred,batch_labels.view(-1,1).float())

    #clear gradients
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameters update
    optimizer.step()

  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 0.222346693277359
Epoch : 2, Loss : 0.17612169682979584
Epoch : 3, Loss : 0.17455346882343292
Epoch : 4, Loss : 0.07796753942966461
Epoch : 5, Loss : 0.1626296043395996
Epoch : 6, Loss : 0.042006343603134155
Epoch : 7, Loss : 0.050746720284223557
Epoch : 8, Loss : 0.06706953793764114
Epoch : 9, Loss : 0.05877821892499924
Epoch : 10, Loss : 0.20709766447544098
Epoch : 11, Loss : 0.17457616329193115
Epoch : 12, Loss : 0.1036694273352623
Epoch : 13, Loss : 0.22585663199424744
Epoch : 14, Loss : 0.07238668203353882
Epoch : 15, Loss : 0.0839124396443367
Epoch : 16, Loss : 0.18577073514461517
Epoch : 17, Loss : 0.08228832483291626
Epoch : 18, Loss : 0.12553849816322327
Epoch : 19, Loss : 0.04986223950982094
Epoch : 20, Loss : 0.09137145429849625
Epoch : 21, Loss : 0.03786439076066017
Epoch : 22, Loss : 0.11767710745334625
Epoch : 23, Loss : 0.1725170910358429
Epoch : 24, Loss : 0.2836732864379883
Epoch : 25, Loss : 0.06566134840250015
Epoch : 26, Loss : 0.027223283424973488
Epoch : 27, Loss : 0.06813656538724899
Epoch : 28, Loss : 0.02045162208378315
Epoch : 29, Loss : 0.03712200000882149
Epoch : 30, Loss : 0.21887342631816864

In [ ]:
# # create model
# model = MySimpleNN(X_train_tensor)

# # define loop for epoch times
# for epoch in range(epochs):
#   # forward pass
#   y_pred = model.forward(X_train_tensor)
#   # loss calculate
#   loss = model.loss_function(y_pred,y_train_tensor)
#   # print(f"Epoch : {epoch+1}, Loss : {loss.item()}")
#   # backward pass
#   loss.backward()
#   # parameters update
#   # Wnew = Wold - learning_rate * dL/dw
#   # Bnew = Bold - l.r * dL/db
#   with torch.no_grad():
#     model.weights -= learning_rate * model.weights.grad
#     model.bias -= learning_rate * model.bias.grad
#   # zero gradients : to make gradient zero after each epochs
#   model.weights.grad.zero_()
#   model.bias.grad.zero_()
#   #print loss in each epochs:
#   print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 3.474470376968384
Epoch : 2, Loss : 3.3310787677764893
Epoch : 3, Loss : 3.1844327449798584
Epoch : 4, Loss : 3.0336225032806396
Epoch : 5, Loss : 2.877162456512451
Epoch : 6, Loss : 2.7181344032287598
Epoch : 7, Loss : 2.5571846961975098
Epoch : 8, Loss : 2.4008243083953857
Epoch : 9, Loss : 2.2457942962646484
Epoch : 10, Loss : 2.0927233695983887
Epoch : 11, Loss : 1.943114161491394
Epoch : 12, Loss : 1.7896608114242554
Epoch : 13, Loss : 1.6455845832824707
Epoch : 14, Loss : 1.5086475610733032
Epoch : 15, Loss : 1.3838467597961426
Epoch : 16, Loss : 1.2739778757095337
Epoch : 17, Loss : 1.1800875663757324
Epoch : 18, Loss : 1.1024317741394043
Epoch : 19, Loss : 1.039892554283142
Epoch : 20, Loss : 0.9901827573776245
Epoch : 21, Loss : 0.9505993127822876
Epoch : 22, Loss : 0.9187081456184387
Epoch : 23, Loss : 0.8925938606262207
Epoch : 24, Loss : 0.8708313703536987
Epoch : 25, Loss : 0.8523830771446228
Epoch : 26, Loss : 0.8365015387535095
Epoch : 27, Loss : 0.822650134563446
Epoch : 28, Loss : 0.8104418516159058
Epoch : 29, Loss : 0.7995941042900085
Epoch : 30, Loss : 0.7898949384689331

# Evaluation

In [ ]:
# Model evaluation using test_loader
model.eval() # set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features,batch_labels in test_loader:

    #forward pass
    y_pred=model(batch_features)
    y_pred=(y_pred>0.8).float() #convert probabilities to binary predictions

    #calculate accuracy for the current batch
    batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# calculate overall accuracy
overall_accuracy=sum(accuracy_list)/len(accuracy_list)
print(f"Accuracy : {overall_accuracy:.4f}")

Accuracy : 0.9484

In [ ]:
# # model evaluation
# with torch.no_grad():
#   y_pred=model.forward(X_test_tensor)
#   y_pred =(y_pred > 0.9).float()
#   accuracy = (y_pred==y_test_tensor).float().mean()
#   print(f"Accuracy : {accuracy.item():.4f}")

Accuracy : 0.6332

# Improvement in out Neural Network Pipelining using nn module

In [ ]:
# building the neural network using nn module
# built-in loss function
# using built-in optimizer
# built-in optimizer

# Defining the Model

In [ ]:
import torch.nn as nn

class MyModel(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

# Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

In [ ]:
#define loss function
loss_function = nn.BCELoss()

In [ ]:
#define optimizer
# Instantiate the new model
model = MyModel(X_train_tensor.shape[1])
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

# Training Pipeline

In [ ]:
# create model
model =MyModel(X_train_tensor.shape[1])

#define loop for epoch times :
for epoch in range(epochs):

  #forward pass
  y_pred=model(X_train_tensor)

  #loss calculate
  loss=loss_function(y_pred,y_train_tensor.reshape(-1,1).float())

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  #zero gradients
  optimizer.zero_grad()

  #print loss in each epochs
  print(f"Epoch : {epoch+1}, Loss : {loss.item()}")

Epoch : 1, Loss : 0.8933460712432861
Epoch : 2, Loss : 0.8933460712432861
Epoch : 3, Loss : 0.8933460712432861
Epoch : 4, Loss : 0.8933460712432861
Epoch : 5, Loss : 0.8933460712432861
Epoch : 6, Loss : 0.8933460712432861
Epoch : 7, Loss : 0.8933460712432861
Epoch : 8, Loss : 0.8933460712432861
Epoch : 9, Loss : 0.8933460712432861
Epoch : 10, Loss : 0.8933460712432861
Epoch : 11, Loss : 0.8933460712432861
Epoch : 12, Loss : 0.8933460712432861
Epoch : 13, Loss : 0.8933460712432861
Epoch : 14, Loss : 0.8933460712432861
Epoch : 15, Loss : 0.8933460712432861
Epoch : 16, Loss : 0.8933460712432861
Epoch : 17, Loss : 0.8933460712432861
Epoch : 18, Loss : 0.8933460712432861
Epoch : 19, Loss : 0.8933460712432861
Epoch : 20, Loss : 0.8933460712432861
Epoch : 21, Loss : 0.8933460712432861
Epoch : 22, Loss : 0.8933460712432861
Epoch : 23, Loss : 0.8933460712432861
Epoch : 24, Loss : 0.8933460712432861
Epoch : 25, Loss : 0.8933460712432861

# Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred =(y_pred > 0.9).float()
  accuracy = (y_pred==y_test_tensor).float().mean()
  print(f"Accuracy : {accuracy.item():.4f}")

Accuracy : 0.6433